# SPDX-FileCopyrightText: 2024 German Aerospace Center (DLR) <https://dlr.de>
#
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
SPDX-FileCopyrightText = "German Aerospace Center (DLR) <https://dlr.de>"
SPDX-License-Identifier = "MIT"
path = ["uv.lock", "src/pycasx/py.typed", ".vscode/*.json"]
