# SPDX-FileCopyrightText: 2024 German Aerospace Center (DLR) <https://dlr.de>
#
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
SPDX-FileCopyrightText = "German Aerospace Center (DLR) <https://dlr.de>"
SPDX-License-Identifier = "MIT"
path = "VERSION"

[[annotations]]
SPDX-FileCopyrightText = "German Aerospace Center (DLR) <https://dlr.de>"
SPDX-License-Identifier = "MIT"
path = "pycasx/py.typed"

[[annotations]]
SPDX-FileCopyrightText = "German Aerospace Center (DLR) <https://dlr.de>"
SPDX-License-Identifier = "MIT"
path = ".vscode/*.json"
