# SPDX-FileCopyrightText: 2024 German Aerospace Center (DLR) <https://dlr.de>
#
# SPDX-License-Identifier: MIT
name: Python linting (pylint)

on:
  push:
    branches:
      - main
      - develop
      - releases/**
  pull_request:
    branches:
      - main
      - develop

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install Python dependencies
        run: |
          uv sync --group ci
      - name: Analysing the code with pylint
        run: |
          pylint --output-format=text pycasx
