# SPDX-FileCopyrightText: 2024 German Aerospace Center (DLR) <https://dlr.de>
#
# SPDX-License-Identifier: MIT
name: Python linting (pylint)

on:
  push:
    branches:
    - main
    - develop
    - releases/**
  pull_request:
    branches:
    - main
    - develop

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[tests]
    - name: Analysing the code with pylint
      run: |
        pylint --fail-under=9 --output-format=text pycasx
