# SPDX-FileCopyrightText: 2024 German Aerospace Center (DLR) <https://dlr.de>
#
# SPDX-License-Identifier: MIT
name: Python tests (pytest)

on:
  push:
    branches:
    - main
    - develop
    - releases/**
  pull_request:
    branches:
    - main
    - develop

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[tests]
    - name: Test with pytest
      run: |
        pytest --cov=pycasx/ --cov-report term-missing --junitxml=report.xml tests/
        coverage xml
